name: tnt_app
description: MVP widget setup for quick PTT access
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  home_widget: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: []
